services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        env_file:
            - .env

    redis:
        container_name: redis
        image: "redis:latest"
        volumes:
            - ./redis-data:/data

    watchtower:
        container_name: watchtower
        image: "containrrr/watchtower"
        environment:
            - WATCHTOWER_POLL_INTERVAL=30
            - WATCHTOWER_CLEANUP=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: app
        restart: always
        depends_on:
            - app
            - redis
