services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        env_file:
            - .env
        develop:
            watch:
                - action: rebuild
                  path: ./src

    redis:
        container_name: redis
        image: "redis:latest"
        volumes:
            - ./redis-data:/data
